# Generated by Django 5.1.1 on 2024-10-23 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='room_type',
        ),
        migrations.AddField(
            model_name='booking',
            name='room_types',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='guests',
            field=models.IntegerField(),
        ),
    ]
