# Generated by Django 5.1.2 on 2024-11-11 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_booking_booking_number_alter_booking_check_in_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_number',
            field=models.CharField(default='5DB96150C2AD', editable=False, max_length=12),
        ),
    ]
